version: "3"
services:
  mysql_container_service:
    container_name: mysql_demo
    hostname: mysql_host
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "1234"
      MYSQL_DATABASE: "instagram"
    ports:
      - "33066:3306"

  spring_container_service:
    container_name: spring_container
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILE: develop
    env_file:
      - .env
    depends_on:
      - mysql_container_service
